CREATE SEQUENCE PATIENT_SEQ
	START WITH 1
	MAXVALUE 99999
	MINVALUE 1
	NOCYCLE
	NOCACHE
	NOORDER;

-----------------------------------------------------------------------------------------------------

CREATE TABLE PATIENT
(
	PA_NUM		CHAR(8 BYTE)					NOT NULL,
	NAME			VARCHAR2(20 BYTE)				NOT NULL,
	SEX			CHAR(1 BYTE)					NOT NULL,
	BIRTH			NUMBER(6)						NOT NULL,
	SUBJECT		VARCHAR2(100 BYTE)				NOT NULL,
	PHONE		VARCHAR2(16 BYTE)				NOT NULL,
	POST_CODE		CHAR(7 BYTE),
	ADDR1		VARCHAR2(200 BYTE),
	ADDR2		VARCHAR2(100 BYTE),
	PHOTO		LONG RAW,
	TREATMENT		VARCHAR2(500 BYTE),
	PRESCRIPTION	VARCHAR2(500 BYTE),

	USE_YN		CHAR(1 BYTE)		DEFAULT 'Y'		NOT NULL,
	REG_ID		VARCHAR2(20 BYTE)	DEFAULT 'admin'	NOT NULL,
	REG_DATE		DATE				DEFAULT SYSDATE	NOT NULL,
	REG_IP		VARCHAR2(15 BYTE)	DEFAULT '127.0.0.1'	NOT NULL,
	UPD_ID		VARCHAR2(20 BYTE)	DEFAULT 'admin'	NOT NULL,
	UPD_DATE		DATE				DEFAULT SYSDATE	NOT NULL,
	UPD_IP		VARCHAR2(15 BYTE)	DEFAULT '127.0.0.1'	NOT NULL
)